### ISSUE TITLE
Lower contrast for NonText?

### ISSUE THREAD

**Issue by oblitum** [arzg/vim-substrata#2]
The tildes (`~`) in NonText area have a high contrast, which makes it stand out when compared withe the low contrast of most other groups. Wouldn't it be better if tildes had lower contrast?

**Comment by lunacookies** [comment]
<img src="https://user-images.githubusercontent.com/31783266/67070755-9cee5c00-f1cc-11e9-84d0-ca3656e5aa2b.png"> Here’s a screenshot of what the tildes look like on my machine. What does it look like for you, or am I missing something?

**Comment by oblitum** [comment]
Sorry, my bad, I had a colorscheme patch lurking in my `.vimrc`.
